using System.Collections.Generic;
using Talos.Definitions;

namespace Talos.Objects
{
    internal static class WeaponRegistry
    {
        internal static readonly IReadOnlyDictionary<string, MeleeWeapon> MeleeWeapons =
            new Dictionary<string, MeleeWeapon>
            {
                ["Stick"] = new MeleeWeapon("Stick", 0, 1, false, true),
                ["Oak Stick"] = new MeleeWeapon("Oak Stick", 0, 1, false, true),
                ["Dirk"] = new MeleeWeapon("Dirk", 0, 2, false, true),
                ["Eppe"] = new MeleeWeapon("Eppe", 0, 2, false, true),
                ["Loures Saber"] = new MeleeWeapon("Loures Saber", 0, 7, false, true),
                ["Harpoon"] = new MeleeWeapon("Harpoon", 0, 11, false, true),
                ["Hatchet"] = new MeleeWeapon("Hatchet", 0, 13, false, true),
                ["Claidheamh"] = new MeleeWeapon("Claidheamh", 0, 14, false, true),
                ["Broad Sword"] = new MeleeWeapon("Broad Sword", 0, 17, false, true),
                ["Dragon Scale Sword"] = new MeleeWeapon("Dragon Scale Sword", 0, 20, false, true),
                ["Wooden Club"] = new MeleeWeapon("Wooden Club", 0, 50, false, true),
                ["Stone Axe"] = new MeleeWeapon("Stone Axe", 0, 95, false, true),
                ["Amber Saber"] = new MeleeWeapon("Amber Saber", 0, 99, true, true, TemuairClass.Warrior),
                ["Diamond Saber"] = new MeleeWeapon("Diamond Saber", 0, 99, true, true, TemuairClass.Warrior),
                ["Emerald Saber"] = new MeleeWeapon("Emerald Saber", 0, 99, true, true, TemuairClass.Warrior),
                ["Ruby Saber"] = new MeleeWeapon("Ruby Saber", 0, 99, true, true, TemuairClass.Warrior),
                ["Sapphire Saber"] = new MeleeWeapon("Sapphire Saber", 0, 99, true, true, TemuairClass.Warrior),
                ["Master Falcata"] = new MeleeWeapon("Master Falcata", 0, 99, true, true, TemuairClass.Warrior),
                ["Master Saber"] = new MeleeWeapon("Master Saber", 0, 99, true, true, TemuairClass.Warrior),
                ["Eclipse"] = new MeleeWeapon("Eclipse", 0, 99, true, true, TemuairClass.Warrior),
                ["Crystal Saber"] = new MeleeWeapon("Crystal Saber", 65, 99, true, true, TemuairClass.Warrior),
                ["Yowien Hatchet"] = new MeleeWeapon("Yowien Hatchet", 80, 99, true, true, TemuairClass.Warrior),
                ["Defiled Ruby Saber"] = new MeleeWeapon("Defiled Ruby Saber", 95, 99, true, true, TemuairClass.Warrior),
                ["Two-Handed Claidhmore"] = new MeleeWeapon("Two-Handed Claidhmore", 0, 71, false, false, TemuairClass.Warrior),
                ["Two-Handed Emerald Sword"] = new MeleeWeapon("Two-Handed Emerald Sword", 0, 77, false, false, TemuairClass.Warrior),
                ["Two-Handed Gladius"] = new MeleeWeapon("Two-Handed Gladius", 0, 86, false, false, TemuairClass.Warrior),
                ["Two-Handed Kindjal"] = new MeleeWeapon("Two-Handed Kindjal", 0, 90, false, false, TemuairClass.Warrior),
                ["Giant Stone Axe"] = new MeleeWeapon("Giant Stone Axe", 0, 93, false, false, TemuairClass.Warrior),
                ["Giant Stone Club"] = new MeleeWeapon("Giant Stone Club", 0, 95, false, false, TemuairClass.Warrior),
                ["Giant Stone Hammer"] = new MeleeWeapon("Giant Stone Hammer", 0, 97, false, false, TemuairClass.Warrior),
                ["Two-Handed Dragon Slayer"] = new MeleeWeapon("Two-Handed Dragon Slayer", 0, 97, false, false, TemuairClass.Warrior),
                ["Hy-brasyl Battle Axe"] = new MeleeWeapon("Hy-brasyl Battle Axe", 0, 99, false, false, TemuairClass.Warrior),
                ["Gold Kindjal"] = new MeleeWeapon("Gold Kindjal", 0, 99, true, false, TemuairClass.Warrior),
                ["Hy-brasy Escalon"] = new MeleeWeapon("Hy-brasy Escalon", 0, 99, true, false, TemuairClass.Warrior),
                ["Empowered Escalon"] = new MeleeWeapon("Empowered Escalon", 0, 99, true, false, TemuairClass.Warrior),
                ["Enchanted Escalon"] = new MeleeWeapon("Enchanted Escalon", 0, 99, true, false, TemuairClass.Warrior),
                ["Master Battle Axe"] = new MeleeWeapon("Master Battle Axe", 0, 99, true, false, TemuairClass.Warrior),
                ["Dane Blade"] = new MeleeWeapon("Dane Blade", 1, 99, true, false, TemuairClass.Warrior),
                ["Astion Blade"] = new MeleeWeapon("Astion Blade", 8, 99, true, false, TemuairClass.Warrior),
                ["Brune Blade"] = new MeleeWeapon("Brune Blade", 15, 99, true, false, TemuairClass.Warrior),
                ["Veltain Sword"] = new MeleeWeapon("Veltain Sword", 15, 99, true, false, TemuairClass.Warrior),
                ["Tempered Veltain Sword"] = new MeleeWeapon("Tempered Veltain Sword", 15, 99, true, false, TemuairClass.Warrior),
                ["Tuned Veltain Sword"] = new MeleeWeapon("Tuned Veltain Sword", 15, 99, true, false, TemuairClass.Warrior),
                ["Blazed Veltain Sword"] = new MeleeWeapon("Blazed Veltain Sword", 15, 99, true, false, TemuairClass.Warrior),
                ["Grum Blade"] = new MeleeWeapon("Grum Blade", 22, 99, true, false, TemuairClass.Warrior),
                ["Andor Saber"] = new MeleeWeapon("Andor Saber", 30, 99, true, false, TemuairClass.Warrior),
                ["Hwarone Guandao"] = new MeleeWeapon("Hwarone Guandao", 45, 99, true, false, TemuairClass.Warrior),
                ["Empowered Hwarone Guandao"] = new MeleeWeapon("Empowered Hwarone Guandao", 55, 99, true, false, TemuairClass.Warrior),
                ["Hellreavers Blade"] = new MeleeWeapon("Hellreavers Blade", 90, 99, true, false, TemuairClass.Warrior),
                ["Ancient Hy-brasyl Axe"] = new MeleeWeapon("Ancient Hy-brasyl Axe", 99, 99, true, false, TemuairClass.Warrior),
                ["Blackstar Night Claw"] = new MeleeWeapon("Blackstar Night Claw", 95, 99, true, true, TemuairClass.Monk),
                ["Eagles Grasp"] = new MeleeWeapon("Eagles Grasp", 90, 99, true, true, TemuairClass.Monk),
                ["Yowien's Fist"] = new MeleeWeapon("Yowien's Fist", 80, 99, true, true, TemuairClass.Monk),
                ["Yowien's Fist1"] = new MeleeWeapon("Yowien's Fist1", 80, 99, true, true, TemuairClass.Monk),
                ["Yowien's Claw"] = new MeleeWeapon("Yowien's Claw", 65, 99, true, true, TemuairClass.Monk),
                ["Yowien's Claw1"] = new MeleeWeapon("Yowien's Claw1", 65, 99, true, true, TemuairClass.Monk),
                ["Stone Fists"] = new MeleeWeapon("Stone Fists", 0, 99, true, true, TemuairClass.Monk),
                ["Phoenix Claws"] = new MeleeWeapon("Phoenix Claws", 0, 99, true, true, TemuairClass.Monk),
                ["Enchanted Kalkuri"] = new MeleeWeapon("Enchanted Kalkuri", 0, 99, true, true, TemuairClass.Monk),
                ["Obsidian"] = new MeleeWeapon("Obsidian", 0, 99, true, true, TemuairClass.Monk),
                ["Nunchaku"] = new MeleeWeapon("Nunchaku", 0, 99, true, true, TemuairClass.Monk),
                ["Tilian Claw"] = new MeleeWeapon("Tilian Claw", 0, 99, true, true, TemuairClass.Monk),
                ["Wolf Claw"] = new MeleeWeapon("Wolf Claw", 0, 50, false, true, TemuairClass.Monk),
                ["Wolf Claws"] = new MeleeWeapon("Wolf Claws", 0, 50, false, true, TemuairClass.Monk),
                ["Ancient Hy-brasyl Azoth"] = new MeleeWeapon("Ancient Hy-brasyl Azoth", 99, 99, true, true, TemuairClass.Rogue),
                ["Inferno Blade"] = new MeleeWeapon("Inferno Blade", 90, 99, true, true, TemuairClass.Rogue),
                ["Blackstar Whip"] = new MeleeWeapon("Blackstar Whip", 95, 99, true, true, TemuairClass.Rogue),
                ["Andor Whip"] = new MeleeWeapon("Andor Whip", 30, 99, true, true, TemuairClass.Rogue),
                ["Thunderfury"] = new MeleeWeapon("Thunderfury", 90, 99, true, false, TemuairClass.Rogue),
                ["Ancient Hy-brasyl Tonfa"] = new MeleeWeapon("Ancient Hy-brasyl Tonfa", 99, 99, true, true, TemuairClass.Monk),
            };

        internal static readonly IReadOnlyDictionary<string, Bow> Bows =
            new Dictionary<string, Bow>
            {
                ["Wooden Bow"] = new Bow("Wooden Bow", 1, 1),
                ["Royal Bow"] = new Bow("Royal Bow", 8, 2),
                ["Jenwir Bow"] = new Bow("Jenwir Bow", 15, 3),
                ["Sen Bow"] = new Bow("Sen Bow", 22, 4),
                ["Andor Bow"] = new Bow("Andor Bow", 30, 4),
                ["Yumi Bow"] = new Bow("Yumi Bow", 45, 5),
                ["Empowered Yumi Bow"] = new Bow("Empowered Yumi Bow", 55, 6),
                ["Thunderfury"] = new Bow("Thunderfury", 90, 6),
            };

        internal static IReadOnlyList<Staff> BuildStaffs(
            Dictionary<string, byte> staffSpells,
            Dictionary<string, byte> minusOneLine,
            Dictionary<string, byte> minusTwoLines,
            Dictionary<string, byte> masterOneLine,
            Dictionary<string, byte> oneLine,
            Dictionary<string, byte> masterPriest,
            Dictionary<string, byte> cradhZeroLine,
            Dictionary<string, byte> fourLinesBecome2Lines,
            Dictionary<string, byte> cradhOneLine)
        {
            return new List<Staff>
            {
                new Staff("Barehand", new Dictionary<string, byte>(staffSpells), 0, 0, false),
                new Staff("Magus Zeus", fourLinesBecome2Lines, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Ares", cradhOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Diana", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Deoch", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Gramail", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Luathas", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Glioca", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Cail", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Sgrios", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Ceannlaidir", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Magus Fiosachd", minusOneLine, 0, 19, false, TemuairClass.Wizard),
                new Staff("Holy Deoch", minusOneLine, 0, 19, false, TemuairClass.Priest),
                new Staff("Holy Gramail", minusOneLine, 0, 19, false, TemuairClass.Priest),
                new Staff("Holy Luathas", minusOneLine, 0, 19, false, TemuairClass.Priest),
                new Staff("Holy Glioca", minusOneLine, 0, 19, false, TemuairClass.Priest),
                new Staff("Holy Cail", minusOneLine, 0, 19, false, TemuairClass.Priest),
                new Staff("Holy Sgrios", minusOneLine, 0, 19, false, TemuairClass.Priest),
                new Staff("Holy Ceannlaidir", minusOneLine, 0, 19, false, TemuairClass.Priest),
                new Staff("Holy Fiosachd", minusOneLine, 0, 19, false, TemuairClass.Priest),
                new Staff("Holy Diana", minusTwoLines, 0, 19, false, TemuairClass.Priest),
                new Staff("Assassin's Cross", minusTwoLines, 27, 99, true, TemuairClass.Priest),
                new Staff("Veltain Staff", minusTwoLines, 15, 99, true, TemuairClass.Wizard),
                new Staff("Andor Staff", minusTwoLines, 30, 99, true, TemuairClass.Wizard),
                new Staff("Skylight Staff", minusTwoLines, 75, 99, true, TemuairClass.Wizard),
                new Staff("Star Crafted Staff", minusTwoLines, 95, 99, true, TemuairClass.Wizard),
                new Staff("Divinities Staff", minusTwoLines, 75, 99, true, TemuairClass.Priest),
                new Staff("Dark Star", minusTwoLines, 95, 99, true, TemuairClass.Priest),
                new Staff("Master Celestial Staff", masterOneLine, 0, 99, true, TemuairClass.Priest),
                new Staff("Enchanted Magus Orb", masterOneLine, 0, 99, true, TemuairClass.Wizard),
                new Staff("Staff of Ages", masterOneLine, 0, 99, true),
                new Staff("Staff of Brilliance", masterOneLine, 0, 99, true),
                new Staff("Staff of Deliverance", masterOneLine, 25, 99, true),
                new Staff("Staff of Clarity", masterOneLine, 50, 99, true),
                new Staff("Staff of Eternity", masterOneLine, 75, 99, true),
                new Staff("Empowered Magus Orb", oneLine, 0, 99, true, TemuairClass.Wizard),
                new Staff("Sphere", oneLine, 1, 99, true, TemuairClass.Wizard),
                new Staff("Shaine Sphere", oneLine, 8, 99, true, TemuairClass.Wizard),
                new Staff("Maron Sphere", oneLine, 15, 99, true, TemuairClass.Wizard),
                new Staff("Chernol Sphere", oneLine, 22, 99, true, TemuairClass.Wizard),
                new Staff("Serpant Sphere", oneLine, 45, 99, true, TemuairClass.Wizard),
                new Staff("Empowered Serpant Sphere", oneLine, 55, 99, true, TemuairClass.Wizard),
                new Staff("Glimmering Wand", oneLine, 65, 99, true, TemuairClass.Wizard),
                new Staff("Glimmering Wand1", oneLine, 65, 99, true, TemuairClass.Wizard),
                new Staff("Yowien Tree Staff", oneLine, 80, 99, true, TemuairClass.Wizard),
                new Staff("Yowien Tree Staff1", oneLine, 80, 99, true, TemuairClass.Wizard),
                new Staff("Dragon Infused Staff", oneLine, 90, 99, true, TemuairClass.Wizard),
                new Staff("Wooden Harp", oneLine, 1, 99, true, TemuairClass.Priest),
                new Staff("Goldberry Harp", oneLine, 8, 99, true, TemuairClass.Priest),
                new Staff("Rosewood Harp", oneLine, 15, 99, true, TemuairClass.Priest),
                new Staff("Ironwood Harp", oneLine, 22, 99, true, TemuairClass.Priest),
                new Staff("Hwarone Lute", oneLine, 45, 99, true, TemuairClass.Priest),
                new Staff("Empowered Hwarone Lute", oneLine, 55, 99, true, TemuairClass.Priest),
                new Staff("Holy Hy-brasyl Baton", oneLine, 65, 99, true, TemuairClass.Priest),
                new Staff("Holy Hy-brasyl Baton1", oneLine, 65, 99, true, TemuairClass.Priest),
                new Staff("Brute's Quill", oneLine, 80, 99, true, TemuairClass.Priest),
                new Staff("Brute's Quill1", oneLine, 80, 99, true, TemuairClass.Priest),
                new Staff("Dragon Emberwood Staff", oneLine, 90, 99, true, TemuairClass.Priest),
                new Staff("Master Divine Staff", masterPriest, 0, 99, true, TemuairClass.Priest),
                new Staff("Empowered Holy Gnarl", cradhZeroLine, 0, 99, true, TemuairClass.Priest),
                new Staff("Eagles Grasp", staffSpells, 90, 99, true, TemuairClass.Monk),
                new Staff("Yowien's Fist", staffSpells, 80, 99, true, TemuairClass.Monk),
                new Staff("Yowien's Fist1", staffSpells, 80, 99, true, TemuairClass.Monk),
                new Staff("Yowien's Claw", staffSpells, 65, 99, true, TemuairClass.Monk),
                new Staff("Yowien's Claw1", staffSpells, 65, 99, true, TemuairClass.Monk),
                new Staff("Blackstar Night Claw", staffSpells, 95, 99, true, TemuairClass.Monk),
                new Staff("Ancient Hy-brasyl Tonfa", staffSpells, 99, 99, true, TemuairClass.Monk),
            };
        }
    }
}
